---
# file: defaults/main.yml

# minimum kernel version
docker_check_kernel: '3.10'

# location of configuration files of docker daemon
docker_daemon_config_directory: "/etc/docker"

# configuration files of docker daemon
docker_daemon_config_file: "{{docker_daemon_config_directory}}/daemon.json"

# configure docker daemon storage driver
docker_daemon_config_storage: "overlay2"

# docker daemon configuration
docker_daemon_config: {}

# docker package name
docker_package: docker

# packages to install/remove
docker_packages: []

# location of configuration files loaded by the init script
docker_init_config_directory: "/etc/sysconfig"

# docker daemon options environment variable
docker_opts: "OPTIONS"

# services to enable/disable
docker_services:
  - { "name": "docker", "state": "started", "enabled": "yes" }

# start docker
docker_start: true

# stop and remove running docker to start a new one when image has been updated
docker_restart: true

# stop and remove running docker to start a new one even if image has not been updated
docker_force_restart: false

