---
# file: tasks/packages.yml

- name: packages - install/remove remotes packages
  when: remotes_packages is defined
  with_items: "{{ remotes_packages|default([]) }}"
  package:
    name: "{{item.name}}"
    state: "{{item.state}}"
  become: yes

