---
# file: tasks/packages.yml

- name: packages - install parted
  when: disks_to_mount is defined
  package:
    name: parted
    state: present
  become: yes

- name: packages - install/remove disks packages
  when: disks_packages is defined
  with_items: "{{ disks_packages|default([]) }}"
  package:
    name: "{{item.name}}"
    state: "{{item.state}}"
  become: yes

