#!/bin/bash
### BEGIN INIT INFO
# Provides: myos
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: System calls from https://github.com/aynicos/myos
### END INIT INFO

set -e

# check system config
[ -r ~/.env ] && . ~/.env || exit 1
type make >/dev/null 2>&1 && [ -d "${MYOS}" ] || exit 2

case "$1" in
  *)
    IFS=$'\n'; exec sh -c "cd ${MYOS} && exec make $@ $(cat /etc/default/myos ~/.env 2>/dev/null)"
esac
