---
# file: tasks/packages.yml

- name: packages - install/remove docker packages
  when: docker_packages is defined
  with_items: "{{ docker_packages|default([]) }}"
  package: name="{{item.name}}" state="{{item.state}}"
  become: yes

- name: packages - add docker GPG key
  when: ansible_os_family|lower == "debian"
  apt_key: url=https://download.docker.com/linux/debian/gpg
  ignore_errors: true
  become: yes

- name: packages - define arch
  set_fact:
    docker_apt_arch: "{% if ansible_machine == 'aarch64' %}arm64{% endif %}{% if ansible_machine == 'x86_64' %}amd64{% endif %}"

- name: packages - add docker APT repository
  when: ansible_os_family|lower == "debian"
  apt_repository:
    repo: deb [arch={{docker_apt_arch}}] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
  become: yes

- name: packages - add docker package
  when: docker_package|length > 0
  package: name="{{docker_package}}" state=present
  become: yes

